### ISSUE TITLE
페이지 기본 퍼블리싱

### ISSUE THREAD

**Issue by ming0o** [Pro-Fit-Dev/frontend#1]
### To-Do
---
- [x] 로그인 & 회원가입 화면 퍼블리싱
- [x] 메인 화면 퍼블리싱
- [x] 헤더/푸터 퍼블리싱
- [x] 지도 화면 퍼블리싱
- [x]  커뮤니티 페이지 퍼블리싱
- [x] 마이 페이지 퍼블리싱

**Comment by ming0o** [comment]
퍼블리싱 전부 끝냈습니다
